[package]
name = "multisig-improved-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.multisig-improved]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.52.3"
default-features = false
