[package]
name = "multisig-interactions"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "=0.52.3"

[dependencies.only-by-multisig]
path = "../only-by-multisig"
